### ISSUE TITLE
Error running 

### ISSUE THREAD

**Issue by waspinator** [p-v-o-s/infragram-js#73]
Following the instructions for developers in the readme I get the following error:

waspinator@ubuntu:~/infragram-js$ nodejs app.js 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.<anonymous> (/home/waspinator/infragram-js/app.js:70:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

after running make I get the following:
make: Nothing to be done for `all'.

after running npm install I get the following errors in the builderror logs:

waspinator@ubuntu:~/infragram-js/node_modules/mongodb/node_modules/bson$ cat builderror.log 
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/waspinator/infragram-js/node_modules/mongodb/node_modules/bson
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 

waspinator@ubuntu:~/infragram-js/node_modules/mongodb/node_modules/bson$ cat /home/waspinator/infragram-js/node_modules/mongodb/node_modules/kerberos/builderror.log
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/waspinator/infragram-js/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 

Ubuntu 14.04 x64

**Comment by waspinator** [comment]
had to run node as root.

**Comment by jywarren** [comment]
Cool, glad you figured it out. Are you looking to tackle some of our open
issues/features?
