### ISSUE TITLE
Delete unapropriate photos on homepage

### ISSUE THREAD

**Issue by logarythm** [p-v-o-s/infragram-js#84]
While i was browsing latests online infrared images, found out 2 offensive photos of naked women.

Can you remove these since IMHO this has nothing to do with the project ?

(browse page 6 and also 16).

**Comment by jywarren** [comment]
Thanks! Solved.

**Comment by logarythm2** [comment]
Hi @jywarren

There's still the image on the server.

Can you please delete it ?
https://infragram.org/upload/1497988288886_nice_cleavage_59_10.jpg

Thanks

**Comment by jywarren** [comment]
Aha - sorry, i tried looking for it and couldn't find it but it's not in
the app itself, just on the server? OK, i'll try. I also added a "report
spam" button which should get published in a week or so. Thanks.
